### ISSUE TITLE
classify the scripts into folders

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/my_scripts#7]
clasify the scripts into folders :)

**Comment by ab-anand** [comment]
Hey are from NIT Hamirpur?

**Comment by srbcheema1** [comment]
@ab-anand  yupp i am

**Comment by sagarkar10** [comment]
Bro please have some kind of respect for the open source community. Bdw I started it. :P

**Comment by srbcheema1** [comment]
@sagarkar10 
it is just a fun task
and thanks for contributions and STAR :smile: 
keep coding .. contributing .. enjoying ..

**Comment by sumandullat** [comment]
i would like to work on it

**Comment by srbcheema1** [comment]
go for it @sumandullat
